language: php

php:
  - "5.3"
  - "5.4"
  
before_script:
- pyrus install pear/PHP_CodeSniffer
- phpenv rehash
- phpcs --standard=platform/build/phpcs/Joomla/ruleset.xml src/

script: phpunit --coverage-text