language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - composer --prefer-source --dev install

script:
  - php bin/phpspec run
