language: php

php:
  - "5.3"
  - "5.4"

before_install:
  - composer self-update

before_script:
  - composer update --dev
  - pear install PHP_CodeSniffer
  - pear channel-discover pear.phing.info
  - pear install phing/phing
  - phpenv rehash

script: phing travis
